In [4]:
import pandas as pd
df = pd.read_csv(r"notebooks\data\ObservationData_ghzcyke.csv")
df=df.drop(columns=['prix', 'Unit'])

# df['Date'] = df['Date'].str.slice(0, 4) + '/' + df['Date'].str.slice(4, 6)
df['Date'] = pd.to_datetime(df['Date'], format='%YM%m')
# Convert the datetime to the desired format
df['Date'] = df['Date'].dt.strftime('%m/%Y')

df['produits'] = df['produits'].str.replace('Arachide décortiquée', 'Arachide')
df['produits'] = df['produits'].str.replace('Riz importé brisé parfumé', 'Riz')
df['produits'] = df['produits'].str.replace('Arachide non décortiquée', 'Patate')
df['produits'] = df['produits'].str.replace('Riz importé brisé ordinaire', 'Manioc')
df['produits'] = df['produits'].str.replace('Riz local décortiqué', 'Manioc')

df = df.rename(columns={'Value': 'prix/KG'})
df = df.rename(columns={'Date': 'date'})
df = df.rename(columns={'régions': 'regions'})


one_hot_encoded = pd.get_dummies(df['produits'])
df = pd.concat([df, one_hot_encoded], axis=1)

one_hot_encoded = pd.get_dummies(df['regions'])
df = pd.concat([df, one_hot_encoded], axis=1)


df

,produits,regions,date,prix/KG,Arachide,Manioc,Maïs,Mil,Niébé,Patate,...,KAOLACK,KEDOUGOU,KOLDA,LOUGA,MATAM,SAINT-LOUIS,SEDHIOU,TAMBACOUNDA,THIES,ZIGUINCHOR
0,Arachide,FATICK,01/2016,550.000000,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
1,Arachide,FATICK,02/2016,425.000000,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
2,Arachide,FATICK,03/2016,486.250000,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
3,Arachide,FATICK,05/2016,550.000000,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
4,Arachide,FATICK,06/2016,566.666667,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14126,Riz,ZIGUINCHOR,04/2023,550.000000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
14127,Riz,ZIGUINCHOR,05/2023,550.000000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
14128,Riz,ZIGUINCHOR,06/2023,500.000000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
14129,Riz,ZIGUINCHOR,07/2023,500.000000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True
14130,Riz,ZIGUINCHOR,08/2023,500.000000,False,False,False,False,False,False,...,False,False,False,False,False,False,False,False,False,True